### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibloadingError

### ISSUE THREAD

**Issue by Bigdoug89** [cloutreactor/release#10]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LibloadingError(LoadLibraryW { source: Os { code: 126, kind: Other, message: "The specified module could not be found." } })', src\main.rs:17:38

Windows 10 Home
GTX 1060
CUDA 11.3

**Comment by korbin** [comment]
The pool was having momentary issues due to increased load - version 0.0.2 addresses these scenarios.
