### ISSUE TITLE
No source code, BEWARE!

### ISSUE THREAD

**Issue by Barnacules** [cloutreactor/release#19]
This isn't source code for the miner but rather a heavily guarded docker container using your computers mining power to mine any coin they want which they keep and award you worthless BitClout. I would avoid this scam entirely and look on YouTube for very detailed videos on the scam before running any of these questionable docker containers created by a group of known scammers in the crypto world.

**Comment by korbin** [comment]
Thanks for the heads up!

**Comment by thehappypenguin** [comment]
I ran about 3 different virus scanners on the binary and can confirm it is more than safe. 

Asking for the source-code for an early mining pool when the developer probably spent weeks optimizing it for profit is totally unreasonable. If you want the source code to make money, it seems like you could consider optimizing it yourself.

**Comment by Stephen1R2** [comment]
He comments on its purpose, not its safety. No one save for the top tier will ever make money with the Bitclout coin.
