### ISSUE TITLE
No Source Code Available?

### ISSUE THREAD

**Issue by maltokyo** [cloutreactor/release#8]
There is literally no code, no Dockerfile, nothing for anyone to see here.  Running this seems extremely risky.  I only see one README file.  Please share source code.

**Comment by marshj1977** [comment]
I found something, but havn't had a chance to look yet.

Check out "Assets 4" on this page: https://github.com/cloutreactor/release/releases
Source : https://github.com/cloutreactor/release/archive/refs/tags/v0.0.1.zip

**Comment by marshj1977** [comment]
D'OH - its just the readme again :(

**Comment by korbin** [comment]
This is a proprietary piece of software. You're free to run it in Docker, however, if you're concerned.

**Comment by Barnacules** [comment]
> There is literally no code, no Dockerfile, nothing for anyone to see here.  Running this seems extremely risky.  I only see one README file.  Please share source code.

I really wish GitHub would do something about this project since it contains no source code but rather a shielded docker container that is using people's computers to mine who knows what while awarding them a useless coin they aren't actually mining.
