### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContentType', src\controller.rs:158:69

### ISSUE THREAD

**Issue by kanshi** [cloutreactor/release#9]
[2021-05-25T12:36:14Z INFO  cloutreactor::metrics] GPU[0] 293.63Mh/s (171W)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContentType', src\controller.rs:158:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-05-25T12:36:19Z INFO  cloutreactor::metrics] GPU[0] 293.61Mh/s (167W)
[2021-05-25T12:36:24Z INFO  cloutreactor::metrics] GPU[0] 293.39Mh/s (57W)
[2021-05-25T12:36:29Z INFO  cloutreactor::metrics] GPU[0] 293.17Mh/s (49W)

Win10, native runtime
GTX 1080 
CUDA 11.3

**Comment by ddkotov** [comment]
redownload .exe file helps for me

**Comment by michaelgiordanod3** [comment]
Closed out the Terminal. ReOpened and restarted and issue seems resolved.

**Comment by Jagermeister56** [comment]
same issue.

**Comment by korbin** [comment]
The pool was having momentary issues due to increased load - version 0.0.2 addresses these scenarios.

**Comment by maltokyo** [comment]
@korbin are earnings with 0.01 protected? I don't see them showing up in my wallet?
